services:
  ##########################
  # ZABBIX AGENT 2
  ###########################
  zabbix-agent2:
    image: zabbix/zabbix-agent2:ubuntu-7.4.3
    container_name: remote-zabbix-agent2
    hostname: ${REMOTE_AGENT_HOSTNAME}
    restart: unless-stopped
    #env_file:
     # - ../.env
    privileged: true
    ports:
      - "${ZBX_PORTS}" # Para poder ser alcanzado por el servidor ZABBIX
    group_add:
      - "${DOCKER_GID}"
    #    networks:
    #      net0:
    #        ipv4_address: ${ZBX_AGENT2_IP}
    #user: "1001:996"
    environment:
      - TZ=${TZ}
      - ZBX_SERVER_HOST=${SERVER_FQDN}
      - ZBX_HOSTNAME=${REMOTE_AGENT_HOSTNAME}
      - ZBX_METADATA=${ZBX_METADATA}
      - ZBX_HOSTINTERFACE=${AGENT_FQDN}
      - ZBX_ACTIVE_ALLOW=${ZBX_ACTIVE_ALLOW}
      - ZBX_REFRESH_ACTIVE_CHECKS=${ZBX_REFRESH_ACTIVE_CHECKS}
      - ZBX_TLSCONNECT=${ZBX_TLSCONNECT}         
      - ZBX_TLSACCEPT=${ZBX_TLSACCEPT}         
      - ZBX_TLSPSKIDENTITY=${ZBX_TLSPSKIDENTITY} 
      - ZBX_TLSPSKFILE=${ZBX_TLSPSKFILE}  
    volumes:
      - /proc:/proc
      - /sys:/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ../psk/zabbix_agentd.psk:/etc/zabbix/zabbix_agentd.psk:ro
